version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # So Jenkins can build/push Docker images

  my-web-app:
    image: my-web-app                 # Prebuilt image name OR use build: .
    container_name: my-django-container
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - jenkins                       # Wait until Jenkins starts before this

volumes:
  jenkins_home:
