# apiVersion: app/v1
# kind: Deployment
# metadata:
#   name: django-app
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: django-app
#   template:
#     metadata:
#       labels:
#         app: django-app
#     spec:
#       containers:
#         - name: django-container
#           image: "purohitjd/my-web-app:tagname"
#           ports:
#             - containerPort: 8000
#           envFrom:
#             - configMapRef:
#                 name: django-config
#             - secretRef:
#                 name: django-secrets
#           readinessProbe:
#             httpGet:
#               path: /
#               port: 8000
#             initialDelaySeconds: 10
#             periodSeconds: 10
#           livenessProbe:
#             httpGet:
#               path: /
#               port: 8000
#             initialDelaySeconds: 30
#             periodSeconds: 30

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-crud-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-webapp
  template:
    metadata:
      labels:
        app: my-webapp
    spec:
      containers:
        - name: my-webapp
          image: purohitjd/crud-django-jenkins:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-crud-prod
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: my-webapp
