apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
stringData:
  secret_key: "django-insecure-0in@)x8$3s+=kx^m5k5mxxsc69=d&wfn_e+w3p53gnf0ea_j=w"
  DB_PASSWORD: "your-db-password"
